language: csharp
solution: Twilio.sln
mono: latest
dotnet: 3.1

services:
  - docker

script:
  - make test
  - make release
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in twilio_inc.pfx.enc -out twilio_inc.pfx -d
  - nuget sign /home/travis/build/twilio/twilio-csharp/src/Twilio/bin/Release/*.nupkg -CertificatePath twilio_inc.pfx -Timestamper http://timestamp.digicert.com
  - nuget verify -All /home/travis/build/twilio/twilio-csharp/src/Twilio/bin/Release/*.nupkg

deploy:
  - provider: script
    script: make docker-build && make docker-push
    skip_cleanup: true
    on:
      branch: main
      tags: true
  - provider: script
    script: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    skip_cleanup: true
    on:
      branch: main
      tags: true

notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: VvnsqrTi9RKxxlZtOL3fAXlXCcKTGbXo6UrB9AGtYRx8xjFgwnKt+RONthbiYXr8auk8XbX5JKyyFB6Vzuc8zzu3a15BlXMtgaiPcRd2KKR4J8RzJbfNw2Ncx+M27mB+/8gXh+4XedjjsurXbJsNj2AUAz/oW4LPgjdURj/H6M0=
